# Generated by Django 2.2 on 2020-12-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_source_site', '0002_auto_20201206_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(null=True, related_name='orders', to='single_source_site.Product'),
        ),
    ]
