# Generated by Django 2.2 on 2020-12-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_source_site', '0003_auto_20201207_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', to='single_source_site.Product'),
        ),
    ]
