# Generated by Django 2.2 on 2021-01-14 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('single_source_site', '0009_category_parent_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='package',
            name='product',
        ),
        migrations.AddField(
            model_name='package',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='single_source_site.Category'),
        ),
        migrations.AlterField(
            model_name='package',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
