# Generated by Django 2.2 on 2021-01-14 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single_source_site', '0010_auto_20210114_1327'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Package_Item',
            new_name='PackageItem',
        ),
    ]
