# Generated by Django 2.2 on 2021-01-14 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('single_source_site', '0011_auto_20210114_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='products',
            field=models.ManyToManyField(through='single_source_site.PackageItem', to='single_source_site.Product'),
        ),
        migrations.AddField(
            model_name='packageitem',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='single_source_site.Package'),
        ),
        migrations.AddField(
            model_name='packageitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='single_source_site.Product'),
        ),
    ]
