# Generated by Django 2.2 on 2021-01-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_source_site', '0012_auto_20210114_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='packages',
            field=models.ManyToManyField(related_name='orders', to='single_source_site.Package'),
        ),
        migrations.AddField(
            model_name='package',
            name='quantity_in_order',
            field=models.IntegerField(default=0),
        ),
    ]
