# Generated by Django 2.2 on 2021-01-27 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single_source_site', '0014_auto_20210126_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='quantity',
            new_name='num_inventory',
        ),
    ]
