# Generated by Django 2.2 on 2021-01-27 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single_source_site', '0015_auto_20210126_2030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
