# Generated by Django 2.2 on 2021-01-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_source_site', '0018_auto_20210127_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
